name: Build and publish a new release

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build release bundle
        run: ./gradlew bundleRelease --no-daemon

      - name: Sign AAB
        uses: ilharp/sign-android-release@v2
        with:
          releaseDir: composeApp/androidApp/build/outputs/bundle/release
          signingKey: ${{ secrets.SIGNING_KEY }}
          keyAlias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          buildToolsVersion: 36.0.0

      - name: Deploy to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: app.reitan.tender
          releaseFiles: composeApp/androidApp/build/outputs/bundle/release/androidApp-release.aab
          mappingFile: composeApp/androidApp/build/outputs/mapping/release/mapping.txt
          debugSymbols: composeApp/androidApp/build/intermediates/merged_native_libs/release/out/lib
          track: internal
          status: draft

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ github.run_number }}
          generate_release_notes: true
