name: Build and publish a new release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        name: Checkout
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up JDK
        uses: actions/setup-java@v5.6.0
        with:
          distribution: 'zulu'
          java-version: '25'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Create next tag
        id: next_tag
        shell: bash
        run: |
          set -euo pipefail
          latest_tag="$(git tag --list 'v[0-9]*' --sort=-v:refname | head -n 1)"
          if [[ -z "${latest_tag}" ]]; then
            latest_tag="v0"
          fi
          current_number="${latest_tag#v}"
          next_number=$((current_number + 1))
          new_tag="v${next_number}"
          echo "new_tag=${new_tag}"
          echo "new_tag=${new_tag}" >> "${GITHUB_OUTPUT}"
          
          if [ $(git tag -l ${new_tag}) ]; then
            git tag --delete ${new_tag}
          fi
          git tag ${new_tag}

      - name: Build release bundle
        run: ./gradlew bundleRelease --no-daemon

      - name: Sign AAB
        id: sign
        uses: ilharp/sign-android-release@v2
        with:
          releaseDir: composeApp/androidApp/build/outputs/bundle/release
          signingKey: ${{ secrets.SIGNING_KEY }}
          keyAlias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Deploy to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: app.reitan.tender
          releaseFiles: ${{ steps.sign.outputs.signedFile }}
          mappingFile: composeApp/androidApp/build/outputs/mapping/release/mapping.txt
          debugSymbols: composeApp/androidApp/build/intermediates/merged_native_libs/release/mergeReleaseNativeLibs/out/lib
          tracks: internal
          status: draft

      - name: Push tag
        run: git push --follow-tags

      - name: Create GitHub release
        uses: softprops/action-gh-release@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ github.run_number }}
          generate_release_notes: true
